version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3.9
    steps:
      - checkout
      - sonar/analyze

orbs:
  sonar: tom-vanbraband-sns/scanner-no-docker@dev:0.0.2

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: SonarCloud
